"use server";

import { randomUUID } from "node:crypto";
import { after } from "next/server";
import { z } from "zod";
import { getSupabase } from "@/lib/auth/session";
import { requireWorkspace, WRITE_ROLES } from "@/lib/auth/workspace";
import { hasRole } from "@/lib/auth/workspace-select";
import { logger } from "@/lib/logger";
import { AdaptationTypeSchema } from "@/lib/schemas/adaptation-type";
import { toPublic, type PublicResult } from "@/lib/adaptation/orchestration/public";
import {
  cancelAdaptationCommand,
  createAdaptationCommand,
  getAdaptationPlan,
  getAdaptationStatus,
  getAdaptationVersion,
  reopenReview,
  retryAdaptationStage,
  startGeneration,
  startPlanning,
  submitPlanReviewCommand,
  type Actor,
  type AdaptationPlanDto,
  type AdaptationVersionDto,
  type EnqueuedDto,
  type SubmitReviewDto,
} from "@/lib/adaptation/orchestration/service";
import type { AdaptationStatusDto } from "@/lib/adaptation/orchestration/status";
import { orchestratorDeps, serviceDeps } from "@/lib/adaptation/orchestration/server";
import { processAdaptationJobs } from "@/lib/adaptation/orchestration/worker";

/**
 * Public application commands for the adaptation pipeline (no UI yet). Every action: resolves the actor on the SERVER (workspace and
 * role never come from the client), validates its input, calls the application service (the only place with domain rules) and
 * answers with a safe, generic result. None of them calls an AI provider: the stages are durable jobs that the scheduler's worker
 * runs (`/api/cron/adaptations`). After a command that enqueues work we ask the worker to take one job soon, purely to cut latency:
 * it is an optimisation, never the guarantee (if it does not run, the next scheduler tick or the reconciler picks the job up).
 */

async function context() {
  const ctx = await requireWorkspace();
  const supabase = await getSupabase();
  const actor: Actor = { userId: ctx.user.id, workspaceId: ctx.workspace.id, canWrite: hasRole(ctx.role, WRITE_ROLES) };
  return { actor, deps: serviceDeps(supabase) };
}

function nudgeWorker() {
  after(async () => {
    try {
      await processAdaptationJobs(orchestratorDeps(), { limit: 1 });
    } catch {
      logger.warn("adaptation_worker_nudge_failed");
    }
  });
}

const Id = z.uuid();

const CreateInput = z.object({
  materialId: Id,
  learnerProfileId: Id.nullable(),
  adaptationType: AdaptationTypeSchema,
  teacherRequest: z.string().trim().max(500).nullable().optional(),
  title: z.string().trim().min(1).max(200).optional(),
  /** Generated by the form once per submit; a double submit reuses the adaptation (and its single reservation). */
  requestKey: z.string().min(8).max(120).optional(),
});

const invalid = <T>(): PublicResult<T> => ({ ok: false, code: "invalid", message: "Revisa los datos y vuelve a intentarlo." });

export async function createAdaptationAction(input: unknown): Promise<PublicResult<{ adaptationId: string }>> {
  const parsed = CreateInput.safeParse(input);
  if (!parsed.success) return invalid();
  const { actor, deps } = await context();
  return toPublic(await createAdaptationCommand(deps, actor, { ...parsed.data, requestKey: parsed.data.requestKey ?? randomUUID() }));
}

/** Entry from an analyzed material: the type is fixed to the accessibility adaptation (the one the pipeline supports today). */
export async function createAdaptationFromMaterialAction(materialId: string, input: { learnerProfileId: string | null; requestKey: string }): Promise<PublicResult<{ adaptationId: string }>> {
  return createAdaptationAction({ materialId, learnerProfileId: input.learnerProfileId, adaptationType: "accessibility", requestKey: input.requestKey });
}

export async function startPlanningAction(adaptationId: string): Promise<PublicResult<EnqueuedDto>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const { actor, deps } = await context();
  const result = await startPlanning(deps, actor, adaptationId);
  if (result.ok) nudgeWorker();
  return toPublic(result);
}

const ReviewInput = z.object({
  schema_version: z.literal(1),
  plan_fingerprint: z.string().regex(/^[a-f0-9]{64}$/),
  entries: z.array(z.record(z.string(), z.unknown())).max(60),
});

/** Only decisions and edits are accepted from the client: the reviewer's identity and the time are set by the server. */
export async function submitPlanReviewAction(adaptationId: string, review: unknown): Promise<PublicResult<SubmitReviewDto>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const parsed = ReviewInput.safeParse(review);
  if (!parsed.success) return invalid();
  const { actor, deps } = await context();
  return toPublic(await submitPlanReviewCommand(deps, actor, adaptationId, { schema_version: 1, plan_fingerprint: parsed.data.plan_fingerprint, entries: parsed.data.entries }));
}

export async function startGenerationAction(adaptationId: string): Promise<PublicResult<EnqueuedDto>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const { actor, deps } = await context();
  const result = await startGeneration(deps, actor, adaptationId);
  if (result.ok) nudgeWorker();
  return toPublic(result);
}

export async function reopenReviewAction(adaptationId: string): Promise<PublicResult<{ status: string }>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const { actor, deps } = await context();
  return toPublic(await reopenReview(deps, actor, adaptationId));
}

export async function retryAdaptationStageAction(adaptationId: string, options?: { acknowledgeAmbiguous?: boolean }): Promise<PublicResult<EnqueuedDto>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const { actor, deps } = await context();
  const result = await retryAdaptationStage(deps, actor, adaptationId, { acknowledgeAmbiguous: options?.acknowledgeAmbiguous === true });
  if (result.ok) nudgeWorker();
  return toPublic(result);
}

export async function cancelAdaptationAction(adaptationId: string): Promise<PublicResult<{ cancelled: boolean; status: string }>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const { actor, deps } = await context();
  return toPublic(await cancelAdaptationCommand(deps, actor, adaptationId));
}

export async function getAdaptationStatusAction(adaptationId: string): Promise<PublicResult<AdaptationStatusDto>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const { actor, deps } = await context();
  return toPublic(await getAdaptationStatus(deps, actor, adaptationId));
}

export async function getAdaptationPlanAction(adaptationId: string): Promise<PublicResult<AdaptationPlanDto>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const { actor, deps } = await context();
  return toPublic(await getAdaptationPlan(deps, actor, adaptationId));
}

export async function getAdaptationVersionAction(adaptationId: string, version?: number): Promise<PublicResult<AdaptationVersionDto>> {
  if (!Id.safeParse(adaptationId).success) return toPublic({ ok: false, code: "not_found" });
  const { actor, deps } = await context();
  return toPublic(await getAdaptationVersion(deps, actor, adaptationId, version ?? null));
}

