import { randomUUID } from "node:crypto";
import { FunctionalProfileSchema } from "@/lib/schemas/functional-profile";
import type { PedagogicalReview } from "@/lib/schemas/pedagogical-review";
import { AdaptationError } from "./errors";
import { cancelAdaptation, createAdaptation, enqueueGeneration, enqueuePlanning, reopenPlanReview, submitPlanReview, type OrchestratorDeps, type StageOutcome } from "./orchestrator";
import { parseStoredAnalysis } from "@/lib/analysis/parse";
import { projectPreserves, projectRestrictions } from "./plan-projection";
import { buildStatusDto, failureOf, isRetryable, type AdaptationStatusDto, type StatusArtifacts } from "./status";
import { NotFoundError, type ArtifactKind, type ArtifactRow } from "./store";
import type { AdaptationStatus } from "./state-machine";
import { isDelivered } from "./state-machine";
import type { PipelineVersions } from "./versions";

/**
 * Application layer of the pipeline: what a Server Action / Route Handler calls (createAdaptation, startPlanning,
 * submitPlanReview, startGeneration, getAdaptationStatus, getAdaptationVersion). It authorizes and narrows; the orchestrator
 * does the work. Authorization is the database's own: every read goes through `AdaptationReader`, which in production is the
 * USER's client (RLS), so another workspace's id is indistinguishable from a missing one (`not_found`, i.e. a 404).
 * The workspace and the role come from the server-resolved actor, never from the request body.
 */

export interface Actor {
  userId: string;
  workspaceId: string;
  /** Computed by the caller from the workspace role (owner/admin/teacher). */
  canWrite: boolean;
}

export interface AdaptationReader {
  getMaterial(id: string): Promise<{ id: string; workspace_id: string; title: string; status: string; analysis: unknown; stage_slug: string | null; grade_slug: string | null; subject_slug: string | null } | null>;
  getLearnerProfile(id: string): Promise<{ id: string; workspace_id: string; stage_slug: string | null; grade_slug: string | null; functional_profile: unknown } | null>;
  getAdaptation(id: string): Promise<{ id: string; workspace_id: string; material_id: string; status: string; current_version: number; delivered_at: string | null } | null>;
  getVersion(adaptationId: string, version: number | null): Promise<{ id: string; version: number; document: unknown; review: unknown; source: string; created_at: string } | null>;
  /** Latest artifact of each requested kind (member-readable under RLS). */
  getArtifacts(adaptationId: string, kinds: readonly ArtifactKind[]): Promise<ArtifactRow[]>;
  /** Display name of a subject of the public catalogue (the sheet's header). Optional: without it the key is shown. */
  getSubjectName?(slug: string): Promise<string | null>;
}

export interface ServiceDeps {
  orchestrator: OrchestratorDeps;
  reader: AdaptationReader;
  /** The versions for NEW adaptations (resolved once, then persisted). */
  resolveVersions: () => PipelineVersions;
  now?: () => Date;
}

export type ServiceError =
  | "forbidden"
  | "not_found"
  | "invalid"
  | "stale_analysis"
  | "invalid_state"
  | "stale_review"
  | "review_required"
  | "unsupported_execution"
  | "action_required"
  | "retry_exhausted"
  | "entitlement_exhausted"
  | "entitlement_unavailable"
  | "entitlement_not_reserved";
export type ServiceResult<T> = { ok: true; data: T } | { ok: false; code: ServiceError; detail?: string[] };

const denied = (actor: Actor): ServiceResult<never> | null => (actor.canWrite ? null : { ok: false, code: "forbidden" });
const notFound: ServiceResult<never> = { ok: false, code: "not_found" };

async function owned(deps: ServiceDeps, actor: Actor, adaptationId: string) {
  const row = await deps.reader.getAdaptation(adaptationId);
  return row && row.workspace_id === actor.workspaceId ? row : null;
}

export interface CreateAdaptationRequest {
  materialId: string;
  learnerProfileId: string | null;
  adaptationType: Parameters<typeof createAdaptation>[1]["adaptationType"];
  teacherRequest?: string | null;
  title?: string;
  /** Generated by the form once per submit; a repeated submit reuses the adaptation. */
  requestKey?: string;
}

export async function createAdaptationCommand(deps: ServiceDeps, actor: Actor, request: CreateAdaptationRequest): Promise<ServiceResult<{ adaptationId: string }>> {
  const no = denied(actor);
  if (no) return no;
  const material = await deps.reader.getMaterial(request.materialId);
  if (!material || material.workspace_id !== actor.workspaceId) return notFound;
  if (material.status !== "analyzed") return { ok: false, code: "invalid", detail: ["El material no está analizado"] };

  let profile = { functional_profile: { schema_version: 1, supports: {}, limits: {}, allowances: {} } as unknown, stage_slug: null as string | null, grade_slug: null as string | null };
  if (request.learnerProfileId) {
    const found = await deps.reader.getLearnerProfile(request.learnerProfileId);
    if (!found || found.workspace_id !== actor.workspaceId) return notFound;
    profile = found;
  }
  const functional = FunctionalProfileSchema.safeParse(profile.functional_profile);
  if (!functional.success) return { ok: false, code: "invalid", detail: ["Perfil funcional no válido"] };

  try {
    const { adaptationId } = await createAdaptation(deps.orchestrator, {
      workspaceId: actor.workspaceId,
      userId: actor.userId,
      materialId: material.id,
      storedAnalysis: material.analysis,
      learnerProfileId: request.learnerProfileId,
      profile: functional.data,
      education: { stage: profile.stage_slug ?? material.stage_slug, grade: profile.grade_slug ?? material.grade_slug, subject: material.subject_slug },
      adaptationType: request.adaptationType,
      teacherRequest: request.teacherRequest ?? null,
      title: (request.title ?? material.title).slice(0, 200),
      requestKey: request.requestKey ?? randomUUID(),
      versions: deps.resolveVersions(),
    });
    return { ok: true, data: { adaptationId } };
  } catch (error) {
    if (error instanceof AdaptationError) {
      if (error.code === "entitlement_exhausted" || error.code === "entitlement_unavailable") return { ok: false, code: error.code };
      return { ok: false, code: error.code === "stale_analysis" ? "stale_analysis" : "invalid", detail: [error.message] };
    }
    if (error instanceof NotFoundError) return notFound;
    throw error;
  }
}

/** Maps a stage outcome to the application's vocabulary (no internal message ever crosses this line). */
function rejection(outcome: StageOutcome): ServiceResult<never> {
  switch (outcome.code) {
    case "entitlement_not_reserved":
      return { ok: false, code: "entitlement_not_reserved" };
    case "stale_review":
      return { ok: false, code: "stale_review" };
    case "execution_unsupported":
      return { ok: false, code: "unsupported_execution" };
    case "plan_review_required":
      return { ok: false, code: outcome.status === "awaiting_plan_review" || outcome.status === "queued" || outcome.status === "planning" ? "review_required" : "invalid_state" };
    case "stale_analysis":
      return { ok: false, code: "stale_analysis" };
    default:
      return { ok: false, code: "invalid_state" };
  }
}

export interface EnqueuedDto {
  status: AdaptationStatus;
  /** The job was already there (a repeated command): nothing new was created. */
  alreadyQueued: boolean;
}

/**
 * Persists the planning job and answers. It NEVER calls a provider: the job is run right after (`POST /api/adaptations/[id]/run`).
 * Idempotent (two clicks, one job). An adaptation that exists but has no job is waiting for THIS command: starting is the
 * teacher's explicit decision, and nothing (not even the recovery cron) starts it for them.
 */
export async function startPlanning(deps: ServiceDeps, actor: Actor, adaptationId: string): Promise<ServiceResult<EnqueuedDto>> {
  const no = denied(actor);
  if (no) return no;
  if (!(await owned(deps, actor, adaptationId))) return notFound;
  const outcome = await enqueuePlanning(deps.orchestrator, adaptationId);
  if (outcome.outcome === "enqueued") return { ok: true, data: { status: outcome.status, alreadyQueued: outcome.reusedJob === true } };
  if (outcome.outcome === "reused") return { ok: true, data: { status: outcome.status, alreadyQueued: true } };
  return rejection(outcome);
}

/** The teacher's review. The reviewer identity and time are set HERE: the client cannot claim to be anyone else. Never generates. */
export interface SubmitReviewDto {
  /** Opaque handle of the saved review (its fingerprint). Generation always uses the server's latest review. */
  reviewFingerprint: string;
  executable: boolean;
  blockers: string[];
  deferredDecisions: string[];
}

export async function submitPlanReviewCommand(deps: ServiceDeps, actor: Actor, adaptationId: string, review: Record<string, unknown>): Promise<ServiceResult<SubmitReviewDto>> {
  const no = denied(actor);
  if (no) return no;
  if (!(await owned(deps, actor, adaptationId))) return notFound;
  const trusted = { ...review, reviewer: { kind: "teacher" }, reviewed_at: (deps.now?.() ?? new Date()).toISOString() };
  const result = await submitPlanReview(deps.orchestrator, adaptationId, trusted);
  if (!result.ok) {
    if (result.code === "stale_review") return { ok: false, code: "stale_review" };
    if (result.code === "plan_review_required") return { ok: false, code: "invalid_state" };
    if (result.code === "stale_analysis") return { ok: false, code: "stale_analysis" };
    return { ok: false, code: "invalid", detail: result.detail.slice(0, 5) };
  }
  return { ok: true, data: { reviewFingerprint: result.reviewFingerprint, executable: result.executable, blockers: result.execution.blockers, deferredDecisions: result.execution.deferred.map((d) => d.id) } };
}

/** Persists the generation job (review, preflight and entitlement checked) and answers. Never calls a provider. Idempotent. */
export async function startGeneration(deps: ServiceDeps, actor: Actor, adaptationId: string): Promise<ServiceResult<EnqueuedDto>> {
  const no = denied(actor);
  if (no) return no;
  if (!(await owned(deps, actor, adaptationId))) return notFound;
  const outcome = await enqueueGeneration(deps.orchestrator, adaptationId);
  if (outcome.outcome === "enqueued") return { ok: true, data: { status: outcome.status, alreadyQueued: outcome.reusedJob === true } };
  if (outcome.outcome === "reused") return { ok: true, data: { status: outcome.status, alreadyQueued: true } };
  return rejection(outcome);
}

/**
 * Manual retry of a FAILED stage. Only for failures the system classed as retryable, or an ambiguous attempt with the explicit
 * acknowledgement. Keeps the entitlement and the persisted versions; creates (or reuses) a job; never a new adaptation.
 */
export async function retryAdaptationStage(deps: ServiceDeps, actor: Actor, adaptationId: string, options: { acknowledgeAmbiguous?: boolean } = {}): Promise<ServiceResult<EnqueuedDto>> {
  const no = denied(actor);
  if (no) return no;
  if (!(await owned(deps, actor, adaptationId))) return notFound;
  const snapshot = await deps.orchestrator.store.getPipeline(adaptationId);
  if (!snapshot) return notFound;
  const failure = failureOf(snapshot);
  // A second click after the first retry took effect: the work is already queued, not an error.
  if (snapshot.adaptation.status !== "failed" && snapshot.jobs.some((j) => j.status === "queued" || j.status === "processing")) return { ok: true, data: { status: snapshot.adaptation.status as AdaptationStatus, alreadyQueued: true } };
  if (snapshot.adaptation.status !== "failed" || !failure || !failure.stage) return { ok: false, code: "invalid_state" };
  if (!isRetryable(failure)) return { ok: false, code: "action_required" };
  if (failure.code === "ambiguous_attempt" && options.acknowledgeAmbiguous !== true) return { ok: false, code: "action_required", detail: ["ambiguous_requires_acknowledgement"] };
  const attempts = snapshot.jobs.filter((j) => j.stage === failure.stage && j.status === "failed").length;
  if (attempts >= (deps.orchestrator.maxManualRetries ?? 3)) return { ok: false, code: "retry_exhausted" };
  const outcome = failure.stage === "planning" ? await enqueuePlanning(deps.orchestrator, adaptationId) : await enqueueGeneration(deps.orchestrator, adaptationId);
  if (outcome.outcome === "enqueued") return { ok: true, data: { status: outcome.status, alreadyQueued: outcome.reusedJob === true } };
  if (outcome.outcome === "reused") return { ok: true, data: { status: outcome.status, alreadyQueued: true } };
  return rejection(outcome);
}

export async function reopenReview(deps: ServiceDeps, actor: Actor, adaptationId: string): Promise<ServiceResult<{ status: AdaptationStatus }>> {
  const no = denied(actor);
  if (no) return no;
  if (!(await owned(deps, actor, adaptationId))) return notFound;
  return { ok: true, data: { status: await reopenPlanReview(deps.orchestrator, adaptationId) } };
}

export async function cancelAdaptationCommand(deps: ServiceDeps, actor: Actor, adaptationId: string): Promise<ServiceResult<{ cancelled: boolean; status: AdaptationStatus }>> {
  const no = denied(actor);
  if (no) return no;
  if (!(await owned(deps, actor, adaptationId))) return notFound;
  return { ok: true, data: await cancelAdaptation(deps.orchestrator, adaptationId) };
}

const STATUS_KINDS: readonly ArtifactKind[] = ["plan", "plan_validation", "plan_review", "execution_report", "pedagogical_review", "deterministic_review"];

/**
 * Gate of `POST /api/adaptations/[id]/run`, BEFORE anything is processed. Running a pending stage (it changes persistent state,
 * calls the provider and can produce a version) takes the capability that starting or retrying it takes: a writer. Reading the
 * status stays open to every member. A role without permission gets the same "not found" as every other command.
 */
export async function authorizeStageRun(deps: ServiceDeps, actor: Actor, adaptationId: string): Promise<ServiceResult<AdaptationStatusDto>> {
  const no = denied(actor);
  if (no) return no;
  return getAdaptationStatus(deps, actor, adaptationId);
}

export async function getAdaptationStatus(deps: ServiceDeps, actor: Actor, adaptationId: string): Promise<ServiceResult<AdaptationStatusDto>> {
  if (!(await owned(deps, actor, adaptationId))) return notFound;
  const snapshot = await deps.orchestrator.store.getPipeline(adaptationId);
  if (!snapshot) return notFound;
  const artifacts = await deps.reader.getArtifacts(adaptationId, STATUS_KINDS);
  const latest = (kind: ArtifactKind) => artifacts.filter((a) => a.kind === kind).at(-1)?.payload as Record<string, unknown> | undefined;
  const validation = latest("plan_validation") as { classification?: { counts: { valid: number; review: number; blocked: number } } } | undefined;
  const execution = latest("execution_report") as { execution?: { ai: string[]; deferred: Array<{ id: string }>; blockers: string[] } } | undefined;
  const merged = latest("pedagogical_review") as { review?: PedagogicalReview; pending?: string[] } | undefined;
  const deterministic = latest("deterministic_review") as { review?: PedagogicalReview } | undefined;
  const extra: StatusArtifacts = {
    planValidation: validation?.classification ? { counts: validation.classification.counts } : null,
    execution: execution?.execution ?? null,
    review: merged?.review ?? deterministic?.review ?? null,
    pending: merged?.pending ?? [],
    hasPlan: artifacts.some((a) => a.kind === "plan"),
    hasPlanReview: artifacts.some((a) => a.kind === "plan_review"),
    hasVersion: (await deps.reader.getVersion(adaptationId, null)) !== null,
  };
  return { ok: true, data: buildStatusDto(snapshot, extra) };
}

export interface PlanDecisionDto {
  id: string;
  target: string;
  action: string;
  intensity: string;
  strategies: string[];
  /** The functional needs behind the decision (dimension keys of the profile's active needs; no learner data). */
  needs: string[];
  supports: string[];
  note: string | null;
  /** The protected requirements this decision carries, as the analysis states them (type + wording). Never an inferred answer. */
  preserves: Array<{ type: string; value: string }>;
  /** Limits a reviewer wrote for this decision in a review of this same plan (empty before any review). */
  restrictions: string[];
  status: "valid" | "review" | "blocked";
  issues: Array<{ flag: string; severity: string; message: string }>;
}

export interface AdaptationPlanDto {
  /** The handle the review must carry: a review made for another plan is refused as stale. */
  planFingerprint: string;
  decisions: PlanDecisionDto[];
  summary: string[];
  counts: { valid: number; review: number; blocked: number };
  review: { submitted: boolean; executable: boolean | null; blockers: string[] };
}

/** The current raw plan for the (future) review screen: decisions with the validator's verdict, never provider output or prompts. */
export async function getAdaptationPlan(deps: ServiceDeps, actor: Actor, adaptationId: string): Promise<ServiceResult<AdaptationPlanDto>> {
  if (!(await owned(deps, actor, adaptationId))) return notFound;
  const artifacts = await deps.reader.getArtifacts(adaptationId, ["plan", "plan_validation", "execution_report", "plan_review"]);
  const plan = artifacts.filter((a) => a.kind === "plan").at(-1);
  const validation = artifacts.filter((a) => a.kind === "plan_validation").at(-1);
  if (!plan || !validation) return { ok: false, code: "not_found" };
  const decisions = (plan.payload as { decisions: Array<Record<string, unknown>> }).decisions;
  const classification = (validation.payload as { classification: { decisions: Array<{ id: string; status: "valid" | "review" | "blocked"; issues: Array<{ flag: string; severity: string; message: string }> }>; counts: AdaptationPlanDto["counts"] } }).classification;
  const execution = artifacts.filter((a) => a.kind === "execution_report").at(-1)?.payload as { execution?: { blockers: string[] } } | undefined;
  const snapshot = await deps.orchestrator.store.getPipeline(adaptationId);
  const analysis = snapshot ? parseStoredAnalysis(snapshot.analysis.analysis).analysis : null;
  const reviews = artifacts.filter((a) => a.kind === "plan_review" && a.input_fingerprint === plan.fingerprint).at(-1)?.payload as { entries?: Array<{ decision_id: string; restrictions?: string[] }> } | undefined;
  return {
    ok: true,
    data: {
      planFingerprint: plan.fingerprint,
      decisions: decisions.map((d) => {
        const c = classification.decisions.find((x) => x.id === d.id);
        return {
          id: String(d.id),
          target: String(d.target),
          action: String(d.action),
          intensity: String(d.intensity),
          strategies: (d.strategies as string[]) ?? [],
          needs: (d.dimensions as string[]) ?? [],
          supports: ((d.supports as Array<{ kind: string }>) ?? []).map((x) => x.kind),
          note: typeof d.note === "string" ? d.note : null,
          preserves: projectPreserves(analysis, (d.preserves as string[]) ?? []),
          restrictions: projectRestrictions(reviews?.entries?.find((e) => e.decision_id === d.id)?.restrictions),
          status: c?.status ?? "valid",
          issues: (c?.issues ?? []).map((i) => ({ flag: i.flag, severity: i.severity, message: i.message })),
        };
      }),
      summary: ((plan.payload as { summary?: string[] }).summary ?? []).slice(0, 6),
      counts: classification.counts,
      review: { submitted: execution !== undefined, executable: execution ? (execution.execution?.blockers.length ?? 0) === 0 : null, blockers: execution?.execution?.blockers ?? [] },
    },
  };
}

export interface AdaptationVersionDto {
  version: number;
  document: unknown;
  review: unknown;
  source: string;
  createdAt: string;
  /** The adaptation is delivered AND this is its current version. */
  delivered: boolean;
  /** Safe to hand to a student as the normal final sheet: delivered and `approved` / `approved_with_warnings`. */
  usable: boolean;
}

export async function getAdaptationVersion(deps: ServiceDeps, actor: Actor, adaptationId: string, version: number | null = null): Promise<ServiceResult<AdaptationVersionDto>> {
  const row = await owned(deps, actor, adaptationId);
  if (!row) return notFound;
  const found = await deps.reader.getVersion(adaptationId, version ?? (row.current_version > 0 ? row.current_version : null));
  if (!found) return notFound;
  const verdict = (found.review as { verdict?: string } | null)?.verdict;
  const delivered = isDelivered(row) && row.current_version === found.version;
  return { ok: true, data: { version: found.version, document: found.document, review: found.review, source: found.source, createdAt: found.created_at, delivered, usable: delivered && (verdict === "approved" || verdict === "approved_with_warnings") } };
}
